name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - six
  - requests=2.24.0
  - mlflow=2.1.1
  - scikit-learn=0.24.1
  - pip:
      - databricks-cli==0.8.7
      - protobuf==3.20.*
      - numpy==1.23.4
      - wandb==0.13.9
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
