name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=20.3.3
  - six
  - mlflow=2.1.1
  - scikit-learn=0.24.1
  - matplotlib=3.6.2
  - pillow=8.1.2
  - pip:
      - databricks-cli==0.8.7
      - protobuf==3.20.*
      - wandb==0.13.9
